"""
Experiment ledger. Every scored run gets ONE record: what ran (config snapshot,
model, git commit), WHY it ran (your hypothesis, --why), and what came out
(metrics + score). Append-only in ours/experiments.jsonl; the table in
ours/RUNS.md is regenerated from the ledger (latest record per run name wins).

    python ours/log_run.py ours/results/base_cite_metrics.json \
        --model deepseek-ai/DeepSeek-V4-Pro --role baseline \
        --why "does forcing citations change the failure profile?"

Re-logging the same name appends a new revision; the table shows the latest.
"""
import argparse
import datetime
import json
import subprocess
from pathlib import Path

import sys as _sys; from pathlib import Path as _P; _sys.path.insert(0, str(_P(__file__).resolve().parent / "stage23")); import score

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / "ours" / "experiments.jsonl"
RUNS_MD = ROOT / "ours" / "RUNS.md"

HEADER = """# Run Table

Generated by `ours/log_run.py` from `ours/experiments.jsonl` — do not edit the table by hand.
Log every run: `python ours/log_run.py <..._metrics.json> --model <model> --why "<hypothesis>"`

**Score** = `65·R + 15·C + 10·E + 10·Q` (our proxy of the official rubric; see `ours/score.py`
for the exact formulas and `ours/stage1/eval_harness.py` + `ours/stage23/eval_harness.py` for the judge prompts). Judge pinned
in `ours/config.json`. Only compare runs scored by the same judge. (+5 voice / +5 UI later.)
"""


def load_ledger():
    if not LEDGER.exists():
        return []
    return [json.loads(l) for l in open(LEDGER, encoding="utf-8")]


def regenerate_runs_md(records):
    latest = {}
    for rec in records:          # later lines override earlier: latest revision wins
        latest[rec["name"]] = rec
    rows = sorted(latest.values(), key=lambda r: r["ts"])
    lines = [HEADER, "| run | date | model | role | R | C | E | Q | **/100** | why |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        s = r["score"]
        q_flag = "" if s["q_source"] == "judged" else "*"
        lines.append(
            f"| `{r['name']}` | {r['ts'][:10]} | {r['model']} | {r['role']} "
            f"| {s['R']:.3f} | {s['C']:.3f} | {s['E']:.2f} | {s['Q']:.2f}{q_flag} "
            f"| **{s['total']:.1f}** | {r['why']} |")
    lines.append("\n`*` = Q assumed, not judged. Full metrics per run: "
                 "`ours/results/<run>_metrics.json`; raw answers + per-question judge "
                 "verdicts alongside. Ledger with config snapshots: `ours/experiments.jsonl`.")
    RUNS_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("metrics")
    ap.add_argument("--why", required=True, help="hypothesis / reason this run exists")
    ap.add_argument("--model", required=True)
    ap.add_argument("--role", default="test", help="baseline | test | rag | ...")
    ap.add_argument("--name", default=None, help="defaults to metrics filename stem")
    ap.add_argument("--q", type=float, default=0.70)
    args = ap.parse_args()

    name = args.name or Path(args.metrics).name.replace("_metrics.json", "")
    git_rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True).stdout.strip()
    rec = {
        "name": name,
        "ts": datetime.datetime.now().isoformat(timespec="seconds"),
        "model": args.model,
        "role": args.role,
        "why": args.why,
        "git": git_rev,
        "config": json.load(open(ROOT / "ours" / "config.json", encoding="utf-8")),
        "score": score.compute(args.metrics, args.q),
        "metrics": json.load(open(args.metrics, encoding="utf-8")),
    }
    with open(LEDGER, "a", encoding="utf-8") as f:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    records = load_ledger()
    regenerate_runs_md(records)
    print(f"logged '{name}' (total {rec['score']['total']:.1f}/100) -> {LEDGER.name}, RUNS.md regenerated "
          f"({len(records)} records)")


if __name__ == "__main__":
    main()
